export const ADD_TOCART = "ADD_TOCART",
  UPDATE_QUANTITY_ITEM_CART = "UPDATE_QUANTITY_ITEM_CART",
  UPDATE_QUANTITY_ITEM_CART_SUCCESS = "UPDATE_QUANTITY_ITEM_CART_SUCCESS",
  DELETE_ITEM_CART = "DELETE_ITEM_CART";
