export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST",
  GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS",
  GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR",
  GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL",
  GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS",
  GET_PRODUCT_TO_BUY = "GET_PRODUCT_TO_BUY",
  SHOW_SELECT_PRICE = "SHOW_SELECT_PRICE";
