export const GET_TOURS_LIST = "GET_TOURS_LIST";
export const GET_TOURS_LIST_SUCCESS = "GET_TOURS_LIST_SUCCESS";
export const GET_TOURS_DETAIL = "GET_TOURS_DETAIL";
export const GET_TOURS_DETAIL_SUCCESS = "GET_TOURS_DETAIL_SUCCESS";
export const GET_LIST_DIA_DIEM = "GET_LIST_DIA_DIEM";
export const GET_LIST_DIA_DIEM_SUCCESS = "GET_LIST_DIA_DIEM_SUCCESS";
export const GET_LIST_GIA_VE = "GET_LIST_GIA_VE";
export const GET_LIST_GIA_VE_SUUCESS = "GET_LIST_GIA_VE_SUUCESS";
